title: ScanNet Indoor Scene Understanding
email: angela.dai@tum.de
description: Website for the ScanNet Indoor Scene Understanding CVPR 2023 Workshop
  ---
baseurl: "/cvpr2023workshop" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
